import http from 'node:http';
import {readFileSync,writeFileSync,renameSync,mkdirSync,readdirSync,unlinkSync} from 'node:fs';
import {randomInt} from 'node:crypto';
import {create,player,move,view} from './game.js';
const dir=process.env.DATA_DIR||'./data';mkdirSync(dir,{recursive:true,mode:0o700});const rooms=new Map(),ttl=7*86400000;
for(const f of readdirSync(dir).filter(f=>/^[A-Z]{6}\.json$/.test(f))){const g=JSON.parse(readFileSync(`${dir}/${f}`));if(Date.now()-g.updated<ttl)rooms.set(g.code,g);else unlinkSync(`${dir}/${f}`);}
const save=g=>{g.updated=Date.now();const path=`${dir}/${g.code}.json`;writeFileSync(path+'.tmp',JSON.stringify(g),{mode:0o600});renameSync(path+'.tmp',path);rooms.set(g.code,g);};
const rates=new Map();function rate(ip){const now=Date.now();let r=rates.get(ip);if(!r||now-r.time>60000){r={time:now,n:0};rates.set(ip,r);}if(++r.n>60)throw Error('Too many requests. Try again in a minute.');}
setInterval(()=>{for(const [ip,r]of rates)if(Date.now()-r.time>60000)rates.delete(ip);for(const [code,g]of rooms)if(Date.now()-g.updated>ttl){rooms.delete(code);unlinkSync(`${dir}/${code}.json`);}},60000).unref();
const assets={'/':['index.html','text/html'],'/app.js':['app.js','text/javascript'],'/style.css':['style.css','text/css']};
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self'; script-src 'self'; frame-ancestors 'none'");const url=new URL(req.url,'http://localhost');const json=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};try{if(req.method==='GET'&&url.pathname==='/health')return json(200,{ok:true});if(req.method==='GET'&&assets[url.pathname]){const [f,t]=assets[url.pathname];res.writeHead(200,{'Content-Type':t,'Cache-Control':'no-cache'});return res.end(readFileSync(new URL(`./public/${f}`,import.meta.url)));}
if(!url.pathname.startsWith('/api/'))return json(404,{error:'Not found'});let b={};if(req.method==='POST'){const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)return json(403,{error:'Invalid origin'});let s='';for await(const chunk of req){s+=chunk;if(s.length>8192)return json(413,{error:'Request too large'});}b=JSON.parse(s||'{}');}
if(req.method==='POST'&&['/api/create','/api/join'].includes(url.pathname)){rate(req.socket.remoteAddress);const name=String(b.name||'').trim();if(!name||name.length>24)throw Error('Enter a name of 1–24 characters.');let g,p;if(url.pathname==='/api/create'){if(rooms.size>=500)throw Error('Server is full. Try again later.');let code;do{code=Array.from({length:6},()=>String.fromCharCode(65+randomInt(26))).join('');}while(rooms.has(code));g=create(code,name);p=g.players[0];}else{g=structuredClone(rooms.get(String(b.code||'').toUpperCase()));if(!g)throw Error('Room not found.');if(g.phase!=='lobby'||g.players.length>=6)throw Error('This room has started or is full.');p=player(name);g.players.push(p);g.rev++;}save(g);return json(200,{token:p.token,view:view(g,p.id)});}
const code=String(b.code||url.searchParams.get('code')||'').toUpperCase();const old=rooms.get(code);if(!old)throw Error('Room not found.');const token=req.headers.authorization?.replace(/^Bearer /,'');const p=old.players.find(p=>p.token===token);if(!p)return json(401,{error:'This seat is unavailable. Rejoin from the lobby.'});if(req.method==='GET'&&url.pathname==='/api/state')return json(200,view(old,p.id));if(req.method==='POST'&&url.pathname==='/api/action'){if(b.rev!==old.rev)return json(409,{error:'The table changed. Please try again.'});const g=structuredClone(old);if(b.type==='leave'){if(g.phase!=='lobby')throw Error('You can leave your seat only in the lobby.');g.players=g.players.filter(x=>x.id!==p.id);if(g.host===p.id)g.host=g.players[0]?.id;g.rev++;if(!g.players.length){rooms.delete(code);unlinkSync(`${dir}/${code}.json`);}else save(g);return json(200,{left:true});}move(g,p.id,b.type,b.data);save(g);return json(200,view(g,p.id));}return json(404,{error:'Not found'});}catch(e){json(400,{error:e.message});}});
server.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('Coup listening on '+server.address().port));
